### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fokinr** [minlexx/whdbx_web#16]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "main.py", line 409, in index
    wspace_kills = zkb.go()
  File "/home/whdbx/whdbx_web_1/classes/zkillboard.py", line 394, in go
    a_kill['killID'] = a_kill['killmail_id']
TypeError: string indices must be integers

**Comment by minlexx** [comment]
@fokinr should be fixed now, thanks!
