### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by Damien-Swift** [minlexx/whdbx_web#23]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 627, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 686, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.7/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/whdbx/whdbx_web_1/main.py", line 569, in signatures
    sig.load(sig_id, self.db)
  File "/home/whdbx/whdbx_web_1/classes/signature.py", line 296, in load
    self.priceData.load_prices(self._config)
  File "/home/whdbx/whdbx_web_1/classes/loot_prices.py", line 39, in load_prices
    self.FULLERITE_C28_PRICE = eveprice.Jita_sell_min(self.FULLERITE_C28_ID)
  File "/home/whdbx/whdbx_web_1/classes/eve_price_resolver.py", line 239, in Jita_sell_min
    orders = esi_calls.market_region_orders(self._cfg, self.THE_FORGE_REGIONID, 'sell', typeid)
  File "/home/whdbx/whdbx_web_1/classes/esi_calls.py", line 396, in market_region_orders
    raise ESIException(error_str)
classes.esi_calls.ESIException: Failed to parse response JSON from CCP ESI server!

**Comment by minlexx** [comment]
Failed to refresh gas material prices. Perhaps some ESI API change, will look soon

**Comment by minlexx** [comment]
Actually was related to https://developers.eveonline.com/blog/article/removal-of-redirect-from-.tech.ccp.is-on-jan-7th

Fixed with ad811259d250fce7665e1bd1139a921710e05e72

Since I stopped playing EVE Online, I stopped reading EVE-related news :sob: 
Thx for report.
