### ISSUE TITLE
Не показал инфу по системе j105719

### ISSUE THREAD

**Issue by GrenRT** [minlexx/whdbx_web#26]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 627, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 690, in _do_respond
    self.hooks.run('before_finalize')
  File "/usr/local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 113, in run
    raise exc
  File "/usr/local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 103, in run
    hook()
  File "/usr/local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 62, in __call__
    return self.callback(**self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/cherrypy/lib/sessions.py", line 703, in save
    cherrypy.session.save()
  File "/usr/local/lib/python3.7/site-packages/cherrypy/lib/sessions.py", line 268, in save
    self._save(expiration_time)
  File "/home/whdbx/whdbx_web_1/classes/redis_session.py", line 77, in _save
    self._redis.set(self.SESSION_PREFIX + str(self.id), val, ex=expires_in_seconds)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1164, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 661, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 673, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 617, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

**Comment by minlexx** [comment]
Мда, горячая, похоже, система была.

P.S. место на серваке почему-то быстро утекло, щас должно быть норм
