### ISSUE TITLE
site down

### ISSUE THREAD

**Issue by xpapahet** [minlexx/whdbx_web#32]
Traceback (most recent call last):
  File "/home/whdbx/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/home/whdbx/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 691, in _do_respond
    self.hooks.run('before_finalize')
  File "/home/whdbx/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
  File "/home/whdbx/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/home/whdbx/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/home/whdbx/.local/lib/python3.6/site-packages/cherrypy/lib/sessions.py", line 705, in save
    cherrypy.session.save()
  File "/home/whdbx/.local/lib/python3.6/site-packages/cherrypy/lib/sessions.py", line 269, in save
    self._save(expiration_time)
  File "/home/whdbx/whdbx_web_1/classes/redis_session.py", line 77, in _save
    self._redis.set(self.SESSION_PREFIX + str(self.id), val, ex=expires_in_seconds)
  File "/home/whdbx/.local/lib/python3.6/site-packages/redis/client.py", line 1164, in set
    return self.execute_command('SET', *pieces)
  File "/home/whdbx/.local/lib/python3.6/site-packages/redis/client.py", line 661, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/whdbx/.local/lib/python3.6/site-packages/redis/client.py", line 673, in parse_response
    response = connection.read_response()
  File "/home/whdbx/.local/lib/python3.6/site-packages/redis/connection.py", line 617, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

**Comment by minlexx** [comment]
:ok_hand: , fixed, seems fine now, thanks!
