### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by PrincessInAOE** [minlexx/whdbx_web#52]
Traceback (most recent call last):
  File "/home/whdbx/whdbx_web_1/_caches/templates/signature.html.py", line 41, in render_body
    sig = context['sig']
  File "/home/whdbx/.local/lib/python3.6/site-packages/mako/runtime.py", line 105, in __getitem__
    return compat_builtins.__dict__[key]
KeyError: 'sig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/whdbx/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/home/whdbx/.local/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/home/whdbx/.local/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/whdbx/.local/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/whdbx/whdbx_web_1/main.py", line 606, in signatures
    return self.tmpl.render('signature.html')
  File "/home/whdbx/whdbx_web_1/classes/template_engine.py", line 44, in render
    return tmpl.render(**self._args)
  File "/home/whdbx/.local/lib/python3.6/site-packages/mako/template.py", line 475, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/whdbx/.local/lib/python3.6/site-packages/mako/runtime.py", line 882, in _render
    **_kwargs_for_callable(callable_, data)
  File "/home/whdbx/.local/lib/python3.6/site-packages/mako/runtime.py", line 919, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/whdbx/.local/lib/python3.6/site-packages/mako/runtime.py", line 946, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/whdbx/whdbx_web_1/_caches/templates/signature.html.py", line 43, in render_body
    raise NameError("'sig' is not defined")
NameError: 'sig' is not defined

**Comment by minlexx** [comment]
??.. On which page?
