### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by IkaruLasa** [minlexx/whdbx_web#56]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/_cprequest.py", line 701, in _do_respond
    self.hooks.run('before_finalize')
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/_cprequest.py", line 95, in run
    self.run_hooks(iter(sorted(self[point])))
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/_cprequest.py", line 117, in run_hooks
    hook()
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/_cprequest.py", line 65, in __call__
    return self.callback(**self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/lib/sessions.py", line 702, in save
    cherrypy.session.save()
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/lib/sessions.py", line 268, in save
    self._save(expiration_time)
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/lib/sessions.py", line 538, in _save
    f.close()
OSError: [Errno 28] No space left on device

**Comment by minlexx** [comment]
This project is no longer developed (development is continued in one of the forks), but it seems your server has run out of storage space (No space left on device).
